aggregation_level: weekly
aggregation_methods: {}
config_path: data.config.yaml
avg_date: "2023-01-01"
temporal_data: False
data:
# clasificacion;linea;categoria;marca
  aggregation_methods:
    black_friday: max
    cantidad: mean
    clasificacion2: max
    cyber_monday: max
    #ee_comercio: mean
    es_festivo: max
    fecha: max
    #icc: mean
    #imacec_comercio: mean
    #imacec_general: mean
    #imacec_no_minero: mean
    #imce_comercio: mean
    #imce_general: mean
    #ine_alimentos: mean
    #ine_supermercados: mean
    linea: max
    categoria: max
    marca: max
    #pib: mean
    stock_disponible_total: sum
    #tavg: mean
    #tmax: mean
    #tmin: mean
    #tpm: mean
    venta_total_neto: mean
  aggregation_methods2:
    black_friday: max
    cantidad: sum
    categoria_2: max
    clasificacion2: max
    cyber_monday: max
    #ee_comercio: mean
    es_festivo: max
    linea: max
    categoria: max
    marca: max
    #icc: mean
    #imacec_comercio: mean
    #imacec_general: mean
    #imacec_no_minero: mean
    #imce_comercio: mean
    #imce_general: mean
    #ine_alimentos: mean
    #ine_supermercados: mean
    linea2: max
    #pib: mean
    #tavg: mean
    #tmax: mean
    #tmin: mean
    #tpm: mean
    venta_total_neto: sum
exog: None
join_keys:
- codigo_producto2
- fecha
sales:
  maestro_path: data/raw/maestro_producto_anonimizado2.csv
  numeric_vars:
    cantidad: cantidad
    costo: costo_total
    venta: venta_total_neto
  path: data/raw/venta_anonimizada_vf.csv
sku: codigo_producto2
stock:
  numeric_vars:
    stock: stock_disponible_total
  path: data/raw/stock_historico_anonimizado.csv

# PROCESSING CONFIGS
impute_method: "mean"
log_transform: True
scaler: "standard"
power_transformer: "yeo-johnson"
categorical_encoding: 'onehot'

# SPLITTING CONFIGS
division_type: 'train_val_test'
cv_splits: 5
test_size: 0.2
val_size: 0.2
